import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { headers } from "next/headers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        {/*This is the head section of the page */}
        <header className="flex items-center justify-between px-6 py-4 border-b-gray-800">
          <div className="flex items-center gap-2">
            <span className="text-xl font-bold text-blue-400 tracking-wide select-none">
              <Link href="/">
                <img src="/logo.svg" alt="" className="h-20 w-auto cursor-pointer p-2" />
                WINGMAN
              </Link>
            </span>
          </div>
          <div className="flex items-center">
            <span className="w-9 h-9 flex items-center justify-center rounded-full bg-blue-500 text-white font-bold text-lg">
              U
            </span>
          </div>

        </header>

        {children}
      </body>
    </html>
  );
}
